import { test, expect } from '../../src/fixtures/harness.js';
import { captureBaseline, resolveLocator, type Baseline } from '../../src/tools/heal.js';

/**
 * Self-healing against real page changes.
 *
 * Every case here is a transformation that actually happens to applications —
 * a rebuild regenerating ids, a copywriter rewording a label, a redesign moving
 * a control into a different container — paired with the refusals that keep the
 * whole idea safe. The refusals matter more than the heals: a healer that always
 * finds something is a test suite that can no longer fail.
 */

test.describe('healing a selector that stopped resolving', () => {
  test('should recover a control whose id was regenerated by a rebuild', async ({ page }) => {
    await page.setContent(`
      <main><form>
        <button id="save-a1b2c3d4e5f6">Save</button>
        <button id="cancel-0f1e2d3c4b5a">Cancel</button>
      </form></main>
    `);

    const baseline = await captureBaseline(page, '#save-a1b2c3d4e5f6');

    // The same page from a later build. Nothing a user would notice changed.
    await page.setContent(`
      <main><form>
        <button id="save-9f8e7d6c5b4a">Save</button>
        <button id="cancel-1a2b3c4d5e6f">Cancel</button>
      </form></main>
    `);

    const { locator, record } = await resolveLocator(page, baseline);

    expect(record.status, 'a regenerated id is the commonest reason a selector rots').toBe(
      'healed',
    );
    expect(await locator?.textContent(), 'the healed locator must reach the Save button').toBe(
      'Save',
    );
    expect(
      record.evidence,
      'the proposal has to show its working, or nobody can review it',
    ).toContain('roleAndName');
    expect(
      record.proposed,
      'the replacement must be a durable hook, not the positional path the heal used',
    ).toBe('role=button[name="Save"]');
  });

  test('should recover a field whose label was reworded, via its name attribute', async ({
    page,
  }) => {
    await page.setContent(`
      <form>
        <label for="qty">Quantity</label>
        <input id="qty" name="quantity" type="number" min="1" max="99" required>
      </form>
    `);

    const baseline = await captureBaseline(page, '#qty');

    // Copy rewritten and the id regenerated. The name attribute is untouched,
    // because the server reads it and changing it would break the form.
    await page.setContent(`
      <form>
        <label for="field-77">Qty</label>
        <input id="field-77" name="quantity" type="number" min="1" max="99" required>
      </form>
    `);

    const { locator, record } = await resolveLocator(page, baseline);

    expect(
      record.status,
      'the name attribute survives redesigns that rewrite everything else',
    ).toBe('healed');
    expect(record.evidence, 'the field name is what carried this match').toContain('fieldName');
    expect(
      record.proposed,
      'a field should be proposed by its name, which the backend depends on, not by an id the next build can regenerate',
    ).toBe('[name="quantity"]');
    expect(await locator?.getAttribute('id')).toBe('field-77');
  });

  test('should recover a link that was reworded and moved, via its href', async ({ page }) => {
    await page.setContent(`
      <div id="toolbar"><a id="cart-1" href="/cart">Add to cart</a></div>
    `);

    const baseline = await captureBaseline(page, '#cart-1');

    // A rebrand: different words, different place in the document, same destination.
    await page.setContent(`
      <section><article><a id="cart-2" href="/cart">Add to bag</a></article></section>
    `);

    const { locator, record } = await resolveLocator(page, baseline);

    expect(
      record.status,
      'the words and the position both changed; where the link goes did not',
    ).toBe('healed');
    expect(record.evidence, 'href is what identified it').toContain('href');
    expect(await locator?.textContent()).toBe('Add to bag');
  });

  test('should reach a control inside an open shadow root', async ({ page }) => {
    // Shadow DOM has broken four separate browser APIs in this harness. A path
    // built with nth-child cannot cross the boundary, so the healer splits it
    // into per-root segments; without that every Web Components control heals to
    // nothing.
    // The root is attached imperatively rather than through customElements:
    // setContent reuses the same window, so a second define() of the same tag
    // throws and the page silently keeps the first definition — which made this
    // test pass against the previous markup instead of the new one.
    const panel = (buttonId: string) => `
      <div id="host"></div>
      <script>
        document.getElementById('host').attachShadow({ mode: 'open' }).innerHTML =
          '<div><button id="${buttonId}">Publish</button></div>';
      </script>
    `;

    await page.setContent(panel('publish-aaaaaaaaaaaa'));
    const baseline = await captureBaseline(page, '#publish-aaaaaaaaaaaa');

    await page.setContent(panel('publish-bbbbbbbbbbbb'));
    const { locator, record } = await resolveLocator(page, baseline);

    expect(record.status, 'a control in a shadow root must be healable like any other').toBe(
      'healed',
    );
    expect(
      await locator?.textContent(),
      'the healed path has to actually address the element through the shadow boundary',
    ).toBe('Publish');
  });
});

test.describe('refusing to heal', () => {
  test('should refuse when several candidates are equally plausible', async ({ page }) => {
    await page.setContent(`
      <table>
        <tr><td>Booking 1</td><td><button id="edit-1">Edit</button></td></tr>
        <tr><td>Booking 2</td><td><button id="edit-2">Edit</button></td></tr>
        <tr><td>Booking 3</td><td><button id="edit-3">Edit</button></td></tr>
      </table>
    `);

    const baseline = await captureBaseline(page, '#edit-2');

    await page.setContent(`
      <table>
        <tr><td>Booking 1</td><td><button id="e-1">Edit</button></td></tr>
        <tr><td>Booking 2</td><td><button id="e-2">Edit</button></td></tr>
        <tr><td>Booking 3</td><td><button id="e-3">Edit</button></td></tr>
      </table>
    `);

    const { locator, record } = await resolveLocator(page, baseline);

    expect(
      record.status,
      'three identical buttons mean the signals cannot say which one the test meant',
    ).toBe('ambiguous');
    expect(
      locator,
      'handing back the first of three would be a coin toss dressed as a decision — and the test would pass',
    ).toBeNull();
    expect(
      record.alternatives.length,
      'the rivals must be listed, so a person can see the collision rather than a bare refusal',
    ).toBeGreaterThan(1);
  });

  test('should refuse when the original selector matches more than one element', async ({
    page,
  }) => {
    await page.setContent(`<button id="go">Go</button>`);
    const baseline = await captureBaseline(page, '#go');

    await page.setContent(`
      <button class="go">Go</button>
      <button class="go">Go</button>
    `);
    // A selector that resolves to two is not a healing problem; it already
    // resolves, to too much.
    const { locator, record } = await resolveLocator(page, { ...baseline, selector: '.go' });

    expect(record.status).toBe('ambiguous');
    expect(
      locator,
      'a strict-mode violation is a loud accurate failure; healing must not convert it into a silent guess',
    ).toBeNull();
  });

  test('should report a removed control as lost rather than finding a substitute', async ({
    page,
  }) => {
    await page.setContent(`
      <button id="export">Export CSV</button>
      <button id="print">Print</button>
    `);

    const baseline = await captureBaseline(page, '#export');

    await page.setContent(`<button id="print">Print</button>`);

    const { locator, record } = await resolveLocator(page, baseline);

    expect(
      record.status,
      'the feature was removed — a healer that finds Print here has turned a regression into a pass',
    ).toBe('lost');
    expect(locator).toBeNull();
  });

  test('should refuse to search a page from a different origin', async ({ page }) => {
    await page.goto('/');

    // Hand-built rather than captured: the point is a baseline recorded
    // elsewhere, which is what happens when a test navigates somewhere it should
    // not have and the element is "missing" for that reason.
    const baseline: Baseline = {
      selector: '#definitely-not-here',
      fingerprint: {
        tag: 'button',
        role: 'button',
        name: 'Add',
        testId: 'todo-submit',
        fieldName: null,
        id: null,
        type: 'submit',
        href: null,
        ancestors: ['html', 'body', 'form'],
        siblingIndex: 1,
        nearbyText: null,
        constraints: null,
      },
      url: 'https://not-the-app.invalid/checkout',
      recordedAt: new Date().toISOString(),
    };

    const { locator, record } = await resolveLocator(page, baseline);

    expect(
      record.status,
      'the element is absent because the run is on the wrong site, and a lookalike here would prove nothing about the app under test',
    ).toBe('wrong-page');
    expect(locator).toBeNull();
    expect(
      record.evidence,
      'the record must name both origins so the mistake is traceable',
    ).toContain('not-the-app.invalid');
  });

  test('should leave a working selector alone even when it now points at different words', async ({
    page,
  }) => {
    await page.setContent(`<button id="primary">Save</button>`);
    const baseline = await captureBaseline(page, '#primary');

    await page.setContent(`
      <button id="primary">Store</button>
      <button id="other">Save</button>
    `);

    const { locator, record } = await resolveLocator(page, baseline);

    expect(
      await locator?.textContent(),
      'second-guessing a working selector would silently re-point the test at the other button',
    ).toBe('Store');
    expect(
      record.status,
      'the selector wins and keeps its element — but its words contradict the baseline, and saying nothing about that is how a recycled id passes in silence',
    ).toBe('drifted');
    expect(record.evidence).toContain('disagree with the baseline');
  });
});

test.describe('capturing a baseline', () => {
  test('should refuse to describe an ambiguous selector', async ({ page }) => {
    await page.setContent(`
      <button class="row-action">Edit</button>
      <button class="row-action">Edit</button>
    `);

    await expect(
      captureBaseline(page, '.row-action'),
      'a baseline taken from the first of two describes an element the test may never have meant, and every later heal inherits that mistake',
    ).rejects.toThrow(/matches 2 elements/);
  });

  test('should refuse to describe a selector that matches nothing', async ({ page }) => {
    await page.setContent(`<button id="only">Only</button>`);
    await expect(captureBaseline(page, '#missing')).rejects.toThrow(/matches nothing/);
  });
});

test.describe('a selector that resolves, to the wrong thing', () => {
  test('should report drift when an id is recycled onto a different control', async ({ page }) => {
    // The silent pass this check exists for. The selector works, so nothing fails,
    // and the test is now exercising a control nobody meant it to touch.
    await page.setContent(`<button id="primary">Delete account</button>`);
    const baseline = await captureBaseline(page, '#primary');

    await page.setContent(`<button id="primary">Subscribe</button>`);
    const { locator, record } = await resolveLocator(page, baseline);

    expect(
      record.status,
      'storing a fingerprint and never reading it on the common path is the same as not storing it',
    ).toBe('drifted');
    expect(record.now, 'the record has to name what it points at now').toBe('button "Subscribe"');
    expect(
      locator,
      'the locator is still handed back — the selector is what the test asked for, and refusing here would fail every legitimate rename',
    ).not.toBeNull();
  });

  test('should report drift when the selector resolves to a hidden element', async ({ page }) => {
    // The two halves of the healer disagreed: count() sees hidden elements and the
    // candidate harvest does not. So a locator could sit on a hidden twin of the
    // control the test meant while a visible one stood next to it.
    await page.setContent(`<button id="go">Go</button>`);
    const baseline = await captureBaseline(page, '#go');

    await page.setContent(`
      <button id="go" style="display:none">Go</button>
      <button id="visible-twin">Go</button>
    `);
    const { record } = await resolveLocator(page, baseline);

    expect(
      record.status,
      'a locator sitting on a hidden twin of the control the test meant is not a healthy locator, and count() alone cannot tell',
    ).toBe('drifted');
    expect(record.evidence, 'the reason has to be readable, not inferred from a status').toContain(
      'hidden',
    );
  });

  test('should still call an unchanged control intact', async ({ page }) => {
    // The check must not turn every run into a drift report.
    await page.setContent(`<form><button id="save">Save</button></form>`);
    const baseline = await captureBaseline(page, '#save');

    await page.setContent(`<form><button id="save">Save</button></form>`);
    const { record } = await resolveLocator(page, baseline);

    expect(record.status).toBe('intact');
  });
});

test.describe('proposing a selector that actually works', () => {
  test('should not propose a selector matching more than one element', async ({ page }) => {
    // Two row links distinguished only by href. The heal is correct and decisive;
    // the obvious proposal is not, because both links are called "Edit".
    await page.setContent(`
      <ul>
        <li><a id="e-aaaaaaaaaaaa" href="/items/1/edit">Edit</a></li>
        <li><a id="e-bbbbbbbbbbbb" href="/items/2/edit">Edit</a></li>
      </ul>
    `);
    const baseline = await captureBaseline(page, '#e-aaaaaaaaaaaa');

    await page.setContent(`
      <ul>
        <li><a id="e-cccccccccccc" href="/items/1/edit">Edit</a></li>
        <li><a id="e-dddddddddddd" href="/items/2/edit">Edit</a></li>
      </ul>
    `);
    const { locator, record } = await resolveLocator(page, baseline);

    expect(record.status, 'href still tells the two apart').toBe('healed');
    expect(await locator?.getAttribute('href')).toBe('/items/1/edit');
    expect(
      record.proposed,
      'advising role=link[name="Edit"] would trade a broken selector for a strict-mode violation; having no unique selector is a finding about the page, not something to paper over',
    ).toBeNull();
  });

  test('should propose a rung that does resolve uniquely when one exists', async ({ page }) => {
    await page.setContent(`<form><input id="qty" name="quantity" type="number"></form>`);
    const baseline = await captureBaseline(page, '#qty');

    await page.setContent(`<form><input id="field-77" name="quantity" type="number"></form>`);
    const { record } = await resolveLocator(page, baseline);

    expect(record.proposed).toBe('[name="quantity"]');
    expect(
      await page.locator(record.proposed ?? 'nothing').count(),
      'the proposal is only advice if following it works',
    ).toBe(1);
  });
});
