import { test, expect } from '@playwright/test';
import {
  describeFingerprint,
  explainMatch,
  isStableId,
  matchAll,
  score,
  textSimilarity,
  wordSetSimilarity,
  type Fingerprint,
} from '../../src/tools/identity.js';

/**
 * The matcher, tested on the changes that actually happen to pages.
 *
 * Every case here is a real way an application moves between two observations:
 * a label is reworded, an id is regenerated by the build, a control is moved
 * into a different container, a row shifts position. The question in each is the
 * same — would a human call these the same element — and the test pins the
 * answer so a weighting change cannot quietly reverse it.
 */

function fingerprint(overrides: Partial<Fingerprint> = {}): Fingerprint {
  return {
    tag: 'button',
    role: 'button',
    name: 'Save',
    testId: null,
    fieldName: null,
    id: null,
    type: null,
    href: null,
    ancestors: ['main', 'form'],
    siblingIndex: 0,
    nearbyText: null,
    constraints: null,
    ...overrides,
  };
}

test.describe('stable versus generated ids', () => {
  test('should reject the ids frameworks invent at build time', () => {
    for (const generated of [
      ':r3:',
      'ember418',
      'ext-gen1043',
      'mat-input-7',
      '9f8a7b6c5d4e3f2a1b0c',
    ]) {
      expect(
        isStableId(generated),
        `${generated} identifies a render, not an element — trusting it makes every rebuild look like a rewrite`,
      ).toBe(false);
    }
  });

  test('should reject a readable stem carrying a generated suffix', () => {
    expect(
      isStableId('submit-button-a1b2c3d4e5f6'),
      'a hash bolted onto a readable name is still a hash',
    ).toBe(false);
  });

  test('should accept an id a person clearly wrote', () => {
    expect(
      isStableId('checkout-submit'),
      'hand-written ids are among the best signals available',
    ).toBe(true);
  });
});

test.describe('scoring a pair', () => {
  test('should match on a test id even when everything else changed', () => {
    const result = score(
      fingerprint({ testId: 'save-btn', name: 'Save', ancestors: ['main', 'form'] }),
      fingerprint({
        testId: 'save-btn',
        name: 'Save changes',
        tag: 'a',
        role: 'link',
        ancestors: ['main', 'aside', 'div'],
        siblingIndex: 4,
      }),
    );

    expect(
      result.confident,
      'a test id surviving a redesign is exactly the case test ids exist for',
    ).toBe(true);
  });

  test('should match a renamed control that kept its place and purpose', () => {
    const result = score(
      fingerprint({ id: 'checkout-submit', name: 'Save' }),
      fingerprint({ id: 'checkout-submit', name: 'Save changes' }),
    );

    expect(
      result.confident,
      'a reworded label is the single most common change a suite has to survive',
    ).toBe(true);
    expect(
      result.signals.find((signal) => signal.signal === 'name')?.matched,
      'and the report must still show that the name is what differed',
    ).toBe(false);
  });

  test('should not be fooled by a rebuilt id', () => {
    const result = score(
      fingerprint({ id: ':r1:', name: 'Save' }),
      fingerprint({ id: ':r9:', name: 'Save' }),
    );

    expect(
      result.confident,
      'the name agrees, so this is still the same button despite two different generated ids',
    ).toBe(true);
    const idSignal = result.signals.find((signal) => signal.signal === 'generatedId');
    expect(
      idSignal?.weight,
      'and the generated id must carry almost no weight either way',
    ).toBeLessThan(0.1);
  });

  test('should refuse to match two different controls that merely look alike', () => {
    const result = score(
      fingerprint({ name: 'Delete', role: 'button' }),
      fingerprint({ name: 'Archive', role: 'button' }),
    );

    expect(
      result.confident,
      'same tag, same role, same position and different names is two controls, not one moved',
    ).toBe(false);
  });

  test('should not call a match confident on structure alone', () => {
    const result = score(
      fingerprint({ name: null, role: null, ancestors: ['main', 'form'], siblingIndex: 2 }),
      fingerprint({ name: null, role: null, ancestors: ['main', 'form'], siblingIndex: 2 }),
    );

    expect(
      result.score,
      'tag, ancestors and position all agree, so the raw score is high',
    ).toBeGreaterThan(0.6);
    expect(
      result.confident,
      'but a page-shaped coincidence is not identity — something meaningful has to agree',
    ).toBe(false);
  });

  test('should match a form field by its name attribute when the label was reworded', () => {
    const result = score(
      fingerprint({
        tag: 'input',
        role: 'textbox',
        name: 'Delivery country',
        fieldName: 'shipCountry',
      }),
      fingerprint({
        tag: 'input',
        role: 'textbox',
        name: 'Where should we send it?',
        fieldName: 'shipCountry',
      }),
    );

    expect(
      result.confident,
      'a label is copy and gets reworded; a field name is a contract with the server and does not',
    ).toBe(true);
  });

  test('should match on the accessible name alone when the role changed', () => {
    // A surviving mutation found this gap. Everywhere else the name matches, the
    // role matches too and `roleAndName` carries the pair — so the name signal
    // was never load-bearing and could have been deleted unnoticed. This is the
    // case that isolates it: a button reworked into a link, which is an ordinary
    // refactor and the exact moment a suite needs the name to still count.
    const result = score(
      fingerprint({ tag: 'button', role: 'button', name: 'Continue to payment' }),
      fingerprint({ tag: 'a', role: 'link', name: 'Continue to payment' }),
    );

    expect(
      result.confident,
      'the accessible name is what most real pages offer, so it must carry a match by itself',
    ).toBe(true);
    expect(
      result.signals.find((signal) => signal.signal === 'roleAndName')?.matched,
      'and it must do so without help from role-and-name, which cannot fire here',
    ).toBe(false);
  });

  test('should not lean on test ids, which most sites do not have', () => {
    // Every site scanned while building this had zero test ids except the
    // fixture we wrote ourselves. A matcher that needs them is a matcher that
    // does not work on the ordinary web.
    const result = score(
      fingerprint({ testId: null, name: 'Add to basket', href: '/cart/add' }),
      fingerprint({ testId: null, name: 'Add to bag', href: '/cart/add' }),
    );

    expect(
      result.confident,
      'no test id on either side, and this is still obviously the same control',
    ).toBe(true);
  });

  test('should match a link by href when its text changed', () => {
    const result = score(
      fingerprint({ tag: 'a', role: 'link', name: 'Read more', href: '/articles/42' }),
      fingerprint({ tag: 'a', role: 'link', name: 'Continue reading', href: '/articles/42' }),
    );

    expect(result.confident, 'a link is mostly its destination').toBe(true);
  });
});

test.describe('fuzzy wording — where similarity helps and where it must not', () => {
  test('should let similar wording confirm a match something structural already carries', () => {
    const result = score(
      fingerprint({ tag: 'a', role: 'link', name: 'Add to basket', href: '/cart/add' }),
      fingerprint({ tag: 'a', role: 'link', name: 'Add to Bag', href: '/cart/add' }),
    );

    expect(result.confident, 'the href carries this; the wording merely agrees with it').toBe(true);
  });

  test('should NOT match two different controls that merely read alike', () => {
    // The trap this weighting exists to avoid. These strings are highly similar
    // and the buttons are not remotely the same, which is exactly how a healed
    // selector ends up pointed at something destructive.
    const result = score(
      fingerprint({ name: 'Delete', role: 'button', ancestors: ['main'], siblingIndex: 1 }),
      fingerprint({ name: 'Delete all', role: 'button', ancestors: ['main'], siblingIndex: 1 }),
    );

    expect(
      result.confident,
      'similar wording must never create a match on its own, or "Delete" heals onto "Delete all"',
    ).toBe(false);
  });

  test('should keep Save and Save as apart', () => {
    const result = score(
      fingerprint({ name: 'Save', role: 'button' }),
      fingerprint({ name: 'Save as', role: 'button' }),
    );

    expect(result.confident, 'the same trap, one letter apart').toBe(false);
  });

  test('should measure wording as a matter of degree, not yes or no', () => {
    expect(
      textSimilarity('Add to basket', 'Add to Bag'),
      'clearly related wording',
    ).toBeGreaterThan(0.5);
    expect(
      textSimilarity('Add to basket', 'Grozā'),
      'a translated label shares nothing as a string — which is why other signals must carry i18n',
    ).toBeLessThan(0.3);
  });

  test('should rank a genuine rewording above a dangerously similar pair', () => {
    // The ordering is the property that matters, and it was wrong. Discarding
    // words of two letters or fewer deleted the "as" from "Save as", so the most
    // dangerous pair on the list scored a perfect 1.00 while a genuine rewording
    // scored 0.50. The discriminating word is often the shortest one.
    const genuine = wordSetSimilarity('Add to the shopping cart', 'Add to cart');
    const deleteTrap = wordSetSimilarity('Delete', 'Delete all');
    const saveTrap = wordSetSimilarity('Save', 'Save as');

    expect(
      genuine,
      'the same control described at two lengths must rank above a pair that differs in scope',
    ).toBeGreaterThan(deleteTrap);
    expect(genuine, 'and above the one-word-apart trap too').toBeGreaterThan(saveTrap);
    expect(
      saveTrap,
      'a single short word changes the meaning entirely, so it must not read as identical',
    ).toBeLessThan(0.9);
  });

  test('should compare surrounding words as a set, since content shifts around a control', () => {
    expect(
      wordSetSimilarity(
        'Total price 24.99 including delivery',
        'Total price 31.50 including delivery',
      ),
      'a price changes and the words around a control do not',
    ).toBeGreaterThan(0.6);
  });
});

test.describe('matching two observations of a page', () => {
  test('should pair the survivors and name what arrived and left', () => {
    const before = [
      fingerprint({ name: 'Save', id: 'save' }),
      fingerprint({ name: 'Cancel', id: 'cancel' }),
      fingerprint({ name: 'Delete', id: 'delete' }),
    ];
    const after = [
      fingerprint({ name: 'Cancel', id: 'cancel' }),
      fingerprint({ name: 'Save changes', id: 'save' }),
      fingerprint({ name: 'Export', id: 'export' }),
    ];

    const result = matchAll(before, after);

    expect(result.pairs, 'Save and Cancel both survive, renamed or not').toHaveLength(2);
    expect(
      result.unmatchedBefore.map((index) => before[index]?.name),
      'Delete is gone, and a drift report exists to say so',
    ).toEqual(['Delete']);
    expect(
      result.unmatchedAfter.map((index) => after[index]?.name),
      'Export is new',
    ).toEqual(['Export']);
  });

  test('should never use one element twice', () => {
    const before = [fingerprint({ name: 'Edit', id: 'edit-1' })];
    const after = [
      fingerprint({ name: 'Edit', id: 'edit-1' }),
      fingerprint({ name: 'Edit', id: 'edit-2' }),
    ];

    const result = matchAll(before, after);

    expect(result.pairs, 'one element cannot be two').toHaveLength(1);
    expect(
      result.pairs[0]?.afterIndex,
      'and the pairing must be the stronger of the two candidates',
    ).toBe(0);
    expect(result.unmatchedAfter, 'the second Edit is genuinely new').toEqual([1]);
  });

  test('should refuse to pair on a high score when nothing decisive agreed', () => {
    // Deliberately the case where score and confidence disagree. Two nameless
    // controls with identical structure score well above the threshold on tag,
    // ancestors and position alone — so a pairing rule that trusted the number
    // would match them, and re-point a selector onto a different element.
    //
    // A "Delete" versus "Delete all" pair does not test this: it scores 0.36 and
    // is refused by the threshold anyway, whichever rule is in force. Same
    // masking trap as the form-submit rule.
    const nameless = fingerprint({
      name: null,
      role: null,
      ancestors: ['main', 'form'],
      siblingIndex: 2,
    });

    expect(
      score(nameless, nameless).score,
      'structure alone puts this comfortably past the threshold',
    ).toBeGreaterThan(0.6);
    expect(
      score(nameless, nameless).confident,
      'and yet nothing that means anything on its own agreed',
    ).toBe(false);

    expect(
      matchAll([nameless], [nameless]).pairs,
      'so it must not be paired — a score without a reason is not identity',
    ).toEqual([]);
  });

  test('should leave everything unmatched when the page is entirely different', () => {
    const result = matchAll(
      [fingerprint({ name: 'Save', id: 'save' })],
      [fingerprint({ tag: 'input', role: 'textbox', name: 'Search', id: 'q' })],
    );

    expect(
      result.pairs,
      'inventing a pairing across a rewrite would heal a selector onto the wrong element',
    ).toEqual([]);
  });
});

test.describe('explaining a match', () => {
  test('should name the signals that agreed and the ones that did not', () => {
    const result = score(
      fingerprint({ id: 'checkout-submit', name: 'Save' }),
      fingerprint({ id: 'checkout-submit', name: 'Save changes' }),
    );

    const explanation = explainMatch(result);

    expect(explanation, 'a bare number tells a reviewer nothing').toContain('agreed on');
    expect(explanation, 'the id agreeing is the reason this is a match').toContain('stableId');
    expect(explanation, 'and the reviewer needs to see what changed').toContain('differed on');
  });

  test('should say plainly when a match is not confident', () => {
    const result = score(
      fingerprint({ name: null, role: null }),
      fingerprint({ name: null, role: null }),
    );

    expect(
      explainMatch(result),
      'an unconfident match must announce itself, since a silent one gets accepted',
    ).toContain('NOT confident');
  });

  test('should describe an element the way a person would refer to it', () => {
    expect(
      describeFingerprint(fingerprint({ testId: 'save-btn', name: 'Save' })),
      'people say "the Save button", not "the element with testid save-btn" — and on most sites there is no test id to say anyway',
    ).toBe('button "Save"');

    expect(
      describeFingerprint(fingerprint({ name: null, fieldName: 'shipCountry', tag: 'input' })),
      'an unlabelled field is best identified by the name the server knows it as',
    ).toBe('input[name=shipCountry]');

    expect(
      describeFingerprint(fingerprint({ id: ':r4:', name: 'Save' })),
      'a generated id is not a name',
    ).toBe('button "Save"');
  });
});
